const OK = 200;
const CREATED = 201;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const DUPLICATE_DATA = 409;
const UNPROCESSEBLE_CONTENT = 422;
const SERVER_ERROR = 500;

export const resCode = {
    OK,
    CREATED,
    BAD_REQUEST,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    UNPROCESSEBLE_CONTENT,
    SERVER_ERROR,
    DUPLICATE_DATA,
};
